### ISSUE TITLE
Search Function

### ISSUE THREAD

**Issue by ShaohuiQian** [usc-bbdl/usc-bbdl.github.io#17]
The Search Function does not work in the "Publication" pages. The search box is just a box without any action. @briancohn

**Comment by briancohn** [comment]
seems to work for me:

http://usc-bbdl.github.io/publications/

**Comment by ShaohuiQian** [comment]
But this one doesn't work:
https://usc-bbdl.github.io/publications/

**Comment by briancohn** [comment]
archived until v2
