### ISSUE TITLE
Current Projects

### ISSUE THREAD

**Issue by briancohn** [usc-bbdl/usc-bbdl.github.io#20]
make this similar to the about page, where the photos of people are. Sample text:

example text content, with example of the related publications.

You also need to add a small section of 'Team' with links to the anchor points on the about page.
![image](https://cloud.githubusercontent.com/assets/4623063/26424524/5c3c6b42-4086-11e7-9a79-736076a0b655.png)

example image

 
![image](https://cloud.githubusercontent.com/assets/4623063/26424595/a74f0888-4086-11e7-8878-17fa060a0a09.png)

**Comment by briancohn** [comment]
Here is the library to use to make the two columns: 
https://www.w3schools.com/bootstrap/bootstrap_grid_examples.asp


and here is sample data:
![image](https://cloud.githubusercontent.com/assets/4623063/26424829/6fae7b42-4087-11e7-83c7-d5bbc17dbe05.png)

**Comment by ShaohuiQian** [comment]
Created
