### ISSUE TITLE
make people in about page segmented into 3 columns

### ISSUE THREAD

**Issue by briancohn** [usc-bbdl/usc-bbdl.github.io#22]
Fully expanded by default

**Comment by briancohn** [comment]
test with 4 collumns first with this layout

make background color of the table grey, text white.
![image](https://cloud.githubusercontent.com/assets/4623063/26427000/cd98e140-408f-11e7-9707-748dc0d8873b.png)

**Comment by briancohn** [comment]
instead of 'VP OF PRODUCT', the subtitles should be CS PHD STUDENT, BME MASTERS STUDENT, POSTDOC, INTERN, etc.

here's the data for all lab members:
![image](https://cloud.githubusercontent.com/assets/4623063/26427110/3fc63402-4090-11e7-88f0-5718c0b3b3e9.png)
please input all of them.

**Comment by ShaohuiQian** [comment]
Should the colour style be the text grey and the background white according to the picture? @briancohn

**Comment by ShaohuiQian** [comment]
Made
