### ISSUE TITLE
create database with papers, authors, and tags (i.e. Neuroscience, motor control)

### ISSUE THREAD

**Issue by briancohn** [usc-bbdl/usc-bbdl.github.io#25]
as a researcher, it's important that I can find papers that are relevant to me.

http://valerolab.org/PublicationsByTopic.php

**Comment by bc** [comment]
@valerolab will fill out the tags:
https://docs.google.com/spreadsheets/u/1/d/18Xno5qeb8pBl2C3h3s4faZ2AkRu27kn5T3F0TPytNFc/edit#gid=0

i.e. `neuroscience,motor_control`

so i can parse them with jekyll

**Comment by valerolab** [comment]
thanks!

-Francisco

On Sep 13, 2017, at 12:34 PM, Brian Cohn <notifications@github.com<mailto:notifications@github.com>> wrote:


@valerolab<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_valerolab&d=DwMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=_X5uCqA9VIXpcWjBgnleTw&m=KcHMkzHD_f87yxcV9Or68rjPMystADeb_j0W535WR_k&s=CmxohIhL1kkSQW1G-IyWMaDQpCzT5bTTStCcWmgRB0k&e=> will fill out the tags:
https://docs.google.com/spreadsheets/u/1/d/18Xno5qeb8pBl2C3h3s4faZ2AkRu27kn5T3F0TPytNFc/edit#gid=0<https://urldefense.proofpoint.com/v2/url?u=https-3A__docs.google.com_spreadsheets_u_1_d_18Xno5qeb8pBl2C3h3s4faZ2AkRu27kn5T3F0TPytNFc_edit-23gid-3D0&d=DwMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=_X5uCqA9VIXpcWjBgnleTw&m=KcHMkzHD_f87yxcV9Or68rjPMystADeb_j0W535WR_k&s=Ap-3R37B7CEgb3mHhJeCG7pm_i_HcdQfjWS1cuZ69pM&e=>

i.e. neuroscience,motor_control

so i can parse them with jekyll
