### ISSUE TITLE
ASB abstract

### ISSUE THREAD

**Issue by anagamori** [usc-bbdl/usc-bbdl.github.io#33]
**Title:** Interactions between Tendon Stiffness and Spindle Afferent Feedback Determine the Magnitude of Involuntary Force Variability

**Link:** [ASB_abstracrt.pdf](https://github.com/usc-bbdl/usc-bbdl.github.io/files/1218671/ASB_abstracrt.pdf)

**Abstract:** 
INTRODUCTION
Tendons influence the transmission of muscle contractions [1]. Moreover, the relative mechanical properties of tendon and muscle determine the changes of muscle and tendon lengths. Therefore, tendon stiffness plays a critical role in the neural control of limb motions and forces [3,4], and is a major factor influencing proprioceptive feedback [2,3].
A basic and popular metric of ‘precision’ in motor control is the ability to produce a constant isometric force. During such tasks, involuntary force variability is an informative and fundamental component of current theories of motor control [5]. We have shown that a closed-loop simulation of peripheral neuromuscular elements can replicate cardinal features of force variability, and can be used to test mechanistic hypotheses about its healthy and pathologic generation/modulation [6]. Thus, we hypothesized that alterations in tendon stiffness would have a distinct influence on the nature of involuntary force variability, and its relationship with proprioceptive feedback.
METHODS
We used a published physiologically-grounded closed-loop simulation of afferented muscle model [6]. The model includes a musculotendon unit, muscle spindle, Golgi tendon organ, and a force- tracking controller, which enables this system to perform force-tracking tasks. In this study, we modeled gastrocnemius muscle, and decreased and increased its tendon stiffness by 50% from a default value. We simulated 20 isometric force trials lasting 100s at 20% of maximal voluntary contraction (MVC) for each level of tendon stiffness. We repeated these trials at different levels of spindle feedback gain. The generated force during the last 90s was analyzed in the time and frequency domains.
RESULTS AND DISCUSSION
As expected, lower tendon stiffness reduced MVC (208 N, 202 N, and 185 N for high, default, and low tendon stiffness) [1].
Figure 1 shows that the overall amplitude of involuntary force variability depended on spindle feedback gain and tendon stiffness in a non-linear manner. In addition, low tendon stiffness resulted in larger reduction in involuntary force variability amplitude at increased spindle feedback gains. Importantly, tendon stiffness had no effect on force variability at lower spindle feedback gains.
These results demonstrate that tendon stiffness, via changes in spindle feedback gain, affect the regulation of involuntary force variability, and agree with suggestions that compliant tendons improve the control of isometric forces [2-4]. This further suggests that decreased or increased stiffness due to musculoskeletal injuries [7] or aging may require adaptation in neural control and coordination among muscles [8].
We also found frequency-specific effects of interactions between tendon stiffness and spindle feedback gain. Decreases in tendon stiffness led to lower high-frequency (5-12 Hz) force variability across spindle feedback gains (Figure 2).
This result implies that high-frequency involuntary force variability, often called physiological tremor, might provide insight into peripheral neuromecahnical interactions. Importantly, pathological tremor, such as occurs in Parkinson’s disease (4-6 Hz), may be exacerbated by the stiffening of tendons which both accompanies aging and is characteristic of the pathology [9].
CONCLUSIONS
Our work emphasizes that, as previously suggested [1-4], the mechanical properties of tendons could be an important—yet overlooked—aspect of force control. Moreover, our physiologically-grounded simulations begin to explain this in a mechanistic way that extends our understanding of healthy and pathologic involuntary force variability. These findings suggest that tendon properties may contribute to the mechanisms of disrupted motor control within certain pathologies, and may therefore represent promising targets for treatment/intervention. 

**Author:** Nagamori A, Laine CM, Jalaleddini K, and Valero-Cuevas FJ	

**BibTex:**
"@article{nagamori2017interactions,
  title={Interactions between Tendon Stiffness and Spindle Afferent Feedback Determine the Magnitude of Involuntary Force Variability},
  author={Nagamori, Akira Laine, Christopher M, Jalaleddini, Kian, and Valero-Cuevas, Francisco J},
  journal={41st Annual Meeting of the American Society of Biomechanics},
  year={2017},
}
"

**Year:** 
2017
**Journal:** 
41st Annual Meeting of the American Society of Biomechanics, Boulder, CO, USA, August 8th – 11th, 2017

**Comment by briancohn** [comment]
done, see https://valerolab.org/abstracts
