### ISSUE TITLE
Here is my ASB information

### ISSUE THREAD

**Issue by marjanin** [usc-bbdl/usc-bbdl.github.io#34]
title:Simple and Two-Element Hill-Type Muscle Models
Cannot Replicate Realistic Muscle Stiffness
link:
http://valerolab.org/marjani/Papers_and_Abstracts/Ali_ASB_2017_Abstract_website.pdf

Full Abstract:

INTRODUCTION
An important functional property of muscle is to
provide stiffness for the limbs [1]. Joint and limb
endpoint stiffnesses are critical to control limb
posture, movement and interaction with the
environment [1,2]. In general, stiffness produces
instantaneous resistance to change in muscle length.
Stiffness is known to be modulated muscle length
(i.e., by joint angles) and muscle activation levels
(i.e. α drive) [3], but the mechanisms that produce
them remain unclear.
Hill-type models are a class of normalized lumpedparameter models of muscle of varying complexities
that can be scaled to approximate specific muscles.
They estimate muscle force as functions of muscle
architecture (physiological cross sectional area and
pennation angle), kinematic state of muscle (length,
and velocity) and the muscle activation level (α
drive) [4,5]. The goal of this project is to assess the
ability of Hill-type models to produce muscle
stiffness [6].

METHODS
In this project, we studied versions of two popular
Hill-type muscle models. The first model is a simple
linear model consisting of series and parallel springs,
a viscous element and a contractile element referred
herein as the simple Hill-type model without forcelength properties (or the Hill-type w/o fl) [4]. The
contractile element converts the α drive to active
muscle force. This model, as presented, did not have
force-length properties. Thus, we modified it by
adding force-length properties to it (i.e., Hill-type w
fl). The two-element Hill-type model incorporates two
parallel active contractile elements for slow and fast
muscle fibers (i.e., Two-Element model) [5]. Note
that the active force-length
Figure 1: Stiffness as a function of muscle length.
properties of muscle (included in the contractile
element) are not equivalent to the Hook’s law stressstrain relationship. Rather, they represent the active
force the muscle can produce at each length for a
given activation level [7].
We estimated muscle stiffness in quasi-static
condition by applying ten small displacements (of
2.5% L0, where L0 is the optimal muscle length) with
the muscle lengths set between 0.5 L0 and 1.8 L0
while the muscle was fully activated. We also
calculated values of stiffness at two lengths (0.8 and
1.2 L0) for α drive ranging between 0 to 100 percent
in steps of 1%.

RESULTS AND DISCUSSION
Figure 1 shows stiffness for all models as a function
of normalized muscle length. To make figures easier
to compare, all figures are normalized to their
maximum absolute value. Stiffness for the simple
Hill-type model without force-length properties does
not depend on muscle length (red). Stiffness varies as
a function of muscle length for the other two models
(blue and green). However, it becomes negative at
some lengths. It is clear that the negative stiffness is
not physically possible since it results in instability.
Both of the two-Element and modified Hill-type41st Annual Meeting of the American Society of Biomechanics, Boulder, CO, USA, August 8th – 11th, 2017
Figure 2: Stiffness as a function of muscle lengths
equal to 0.8 L0 (solid lines) and 1.2 L0 (dashed lines).
models, however, show patterns similar to that
reported in experiments in their non-negative regions
[8]. Figure 2 shows the stiffness for all models as a
function of muscle activation level at two
representative muscle lengths (0.8, 1.2 L0). Once
again, stiffness is not a function of muscle activation
in the absence of force-length properties (red).
Stiffness for the two-Element model does vary with
the muscle activation level for the other two models
in a length-dependent manner (blue and green).
Interestingly, this change in the stiffness was
consistent with the relative proportions of the
derivatives of the active and passive parts of the
force-length curve. i.e. the more the activation, the
larger the weight of the active part. This result is
expected considering that activation applies only to
the active part of the force-length curve of muscle.
As can be seen on the figures, the stiffness can be
negative for both length dependent models (blue and
green) when the muscle length is longer than L0,
which demonstrates that the models fail to replicate
realistic muscle stiffness.

CONCLUSIONS
Our results show the simplest Hill-type model fails
to reproduce both muscle length and activation
dependence of stiffness. The modified and twoelement Hill-type muscle models produced stiffness
dependence on muscle length and activation, but
invariably produce negative stiffness at some muscle
lengths, which is not physically realistic. Although
force-length properties are very important in
explaining stiffness [1,2], Hill-type models cannot
replicate realistic muscle stiffness even when
including presence of force-length properties.
Future work will explore if dynamic simulations (as
opposed to this quasi-static version) and other
extensions, such as the inclusion of force-velocity
properties, can produce realistic muscle stiffness. If
those efforts are unsuccessful, other models such as
population-, fiber- and sarcomere-based—although
more computationally complex—would need to be
preferred.

REFERENCES
1. Inouye J. M, and Valero-Cuevas F. J. PLoS
Comput Biol, 12, p. e1004737, 2016.
2. Babikian S, et al. J. Nonlinear Sci., 26, 1293–
1309, 2016.
3. Mirbagheri M. M. Exp. Brain Res.et al. 135, 423–
436, 2000.
4. Shadmehr R, and Wise S. P, MIT press, 2005.
5. Lee S. S. M, et al. J. Biomech., 46, 2288–2295,
2013.
6. Valero-Cuevas F. J, et al. IEEE Rev. Biomed.
Eng, 12, 110-135, 2009
7. Valero-Cuevas F. J. Fundamentals of
neuromechanics, Springer, 2015
8. Weiss P.L, et al. J. Biomech., 19, 727-735,1986.

ACKNOWLEDGMENTS
This study was supported by NIH-NIAMS under
award numbers R01AR050520 and R01AR052345
grants to FVC. This project is also supported by USC
graduate school’s provost fellowship to A.

Authors:  Ali Marjaninejad, Babak Taherian, Kian Jalaleddini, and Francisco J Valero-Cuevas

Bibtex:
"
@inproceedings{,
address = {Boulder, Colorado, USA},

booktitle = {American Society for Biomechanics},

pages = {2},
title = {{Simple and Two-Element Hill-Type Muscle Models Cannot Replicate Realistic Muscle Stiffness}},

year = {2017}
}

"

Year:
2017

Conf:
ASB

SupplementalLink (Link to the poster):
http://valerolab.org/marjani/Papers_and_Abstracts/Ali_ASB_2017_Poster_website.pdf

**Comment by briancohn** [comment]
got it

**Comment by briancohn** [comment]
valerolab.org/abstracts
