### ISSUE TITLE
Adding my ASB abstract

### ISSUE THREAD

**Issue by kian-ja** [usc-bbdl/usc-bbdl.github.io#35]
@inproceedings{jalaleddini2017ASB,
  title={Evidence That Tuning of Muscle Spindles Can Be Decoupled from Muscle Activation},
  author={Jalaleddini, Kian and Kutch, and Nagamori, Akira, and Laine Christopher, and Golkar, Mahsa A., and Kearney, Robert E., and Valero-Cuevas Francisco J}.
booktitle={Proceedings of the 41st Annual Meeting of the American Society of Biomechanics, Long Beach, CA},
  volume={},
  year={2017}
}

Title: Evidence That Tuning of Muscle Spindles Can Be Decoupled from Muscle Activation
Link:
Author: Kian Jalaleddini, Akira Nagamori, Christopher M. Laine, Mahsa A. Golkar, Robert E. Kearney, Francisco J Valero-Cuevas
BibTex: see above
Year: 2017
Journal: Proceedings of the 41st Annual Meeting of the American Society of Biomechanics, Boulder, CO
SupplementalLink
[ASB2017_Poster_Kian.pdf](https://github.com/usc-bbdl/usc-bbdl.github.io/files/1219456/ASB2017_Poster_Kian.pdf)

**Comment by briancohn** [comment]
done, see https://valerolab.org/abstracts, verify that it is correct please @kian-ja
