### ISSUE TITLE
"Companion video lectures from BKN504" Doesn't work

### ISSUE THREAD

**Issue by marjanin** [usc-bbdl/usc-bbdl.github.io#38]
Hi,
I was going to forward some students to the lectures from previous years but the link "Companion video lectures from BKN504" doesn't work.
Please let me know and thank you in advance,
Ali

**Comment by briancohn** [comment]
What page?

**Comment by briancohn** [comment]
![image](https://user-images.githubusercontent.com/4623063/29676812-025a678a-88ae-11e7-9e53-a8a2b1a65428.png)
adding these to website now

**Comment by briancohn** [comment]
![image](https://user-images.githubusercontent.com/4623063/29677486-25388488-88b0-11e7-8cd6-6bedeba85bff.png)
also added helpful image to let users know what to expect
