### ISSUE TITLE
Add Dan's paper to the website

### ISSUE THREAD

**Issue by danhagen** [usc-bbdl/usc-bbdl.github.io#39]
Similar movements are associated with drastically different muscle contraction velocities

Paper/Hagen2017Similar.pdf

We investigated how kinematic redundancy interacts with the neurophysiological control mechanisms required for smooth and accurate, rapid limb movements. Biomechanically speaking, tendon excursions are over-determined because the rotation of few joints determines the lengths and velocities of many muscles. But how different are the muscle velocity profiles induced by various, equally valid hand trajectories? We used an 18-muscle sagittal-plane arm model to calculate 100,000 feasible shoulder, elbow, and wrist joint rotations that produced valid basketball free throws with different hand trajectories, but identical initial and final hand positions and velocities. We found large differences in the eccentric and concentric muscle velocity profiles across many trajectories; even among similar trajectories. These differences have important consequences to their neural control because each trajectory will require unique, time-sensitive reflex modulation strategies. As Sherrington mentioned a century ago, failure to appropriately silence the stretch reflex of _any one_ eccentrically contracting muscle will disrupt movement. Thus, trajectories that produce faster or more variable eccentric contractions will require more precise timing of reflex modulation across motoneuron pools; resulting in higher sensitivity to time delays, muscle mechanics, excitation/contraction dynamics, noise, errors and perturbations. By combining fundamental concepts of biomechanics and neuroscience, we propose that kinematic and muscle redundancy are, in fact, severely limited by the need to regulate reflex mechanisms in a task-specific and time-critical way. This in turn has important consequences to the learning and execution of accurate, smooth and repeatable movements—and to the rehabilitation of everyday limb movements in developmental and neurological conditions, and stroke.

Hagen DA, Valero-Cuevas FJ

"@article{hagen2017similar,
  title={Similar movements are associated with drastically different muscle contraction velocities},
  author={Hagen, Daniel A and Valero-Cuevas, Francisco J},
  journal={Journal of Biomechanics},
  year={2017},
  publisher={Elsevier}
}
"

2017

Journal of Biomechanics

**Comment by briancohn** [comment]
got it! adding this now

**Comment by briancohn** [comment]
modifications
`Paper/Hagen2017Similar.pdf --> Papers/Hagen2017Similar.pdf` 

`"@Article{-> "@article{`

BibTex Button output:
```
@article{hagen2017similar,
title={Similar movements are associated with drastically different muscle contraction velocities},
author={Hagen, Daniel A and Valero-Cuevas, Francisco J},
journal={Journal of Biomechanics},
year={2017},
publisher={Elsevier}
}```
<img width="991" alt="pasted_image_8_24_17__9_20_am" src="https://user-images.githubusercontent.com/4623063/29676674-8a0ec104-88ad-11e7-9b74-2da4332862fa.png">
