### ISSUE TITLE
Hi: Please add my paper to the website. Thanks

### ISSUE THREAD

**Issue by marjanin** [usc-bbdl/usc-bbdl.github.io#41]
Hi: Please add my paper to the website. Thanks

Title:
Finger movements are mainly represented by a linear transformation of energy in band-specific ECoG signals

Link:http://ieeexplore.ieee.org/abstract/document/8036991/

Abstract:
Electrocardiogram (ECoG) recordings are very attractive for Brain Machine Interface (BMI) applications due to their balance between good signal to noise ratio and minimal invasiveness. The design of ECoG signal decoders is an open research area to date which requires a better understanding of the nature of these signals and how information is encoded in them. In this study, a linear and a non-linear method, Linear Regression Model (LRM) and Artificial Neural Network (ANN) respectively, were used to decode finger movements from energy in band-specific ECoG signals. It is shown that the ANN only slightly outperformed the LRM, which suggests that finger movements are mainly represented by a linear transformation of energy in band-specific ECoG signals. In addition, comparing our results to similar Electroencephalogram (EEG) studies illustrated that the spatio-temporal summation of multiple neural signals is itself linearly correlated with movement, and is not an artifact introduced by the scalp or cranium. Furthermore, a new algorithm was employed to reduce the number of spectral features of the input signals required for either of the decoding methods.

Authors:

Ali Marjaninejad, Babak Taherian, Francisco J. Valero-Cuevas
BibTex:

@inproceedings{marjaninejad2017finger,
  title={Finger movements are mainly represented by a linear transformation of energy in band-specific ECoG signals},
  author={Marjaninejad, Ali and Taherian, Babak and Valero-Cuevas, Francisco J},
  booktitle={Engineering in Medicine and Biology Society (EMBC), 2017 39th Annual International Conference of the IEEE},
  pages={986--989},
  year={2017},
  organization={IEEE}
}

Year:
2017

Journal:
Published in: Engineering in Medicine and Biology Society (EMBC), 2017 39th Annual International Conference of the IEEE

SupplementalLink:
The code is shared on github at:
https://github.com/marjanin/Ali-Marjaninejad-et.-al.-2017-code

**Comment by briancohn** [comment]
@marjanin add pdf plz

**Comment by bc** [comment]
@inproceedings{marjaninejad2017finger,
title={Finger movements are mainly represented by a linear transformation of energy in band-specific ECoG signals},
author={Marjaninejad, Ali and Taherian, Babak and Valero-Cuevas, Francisco J},
booktitle={Engineering in Medicine and Biology Society (EMBC), 2017 39th Annual International Conference of the IEEE},
pages={986--989},
year={2017},
organization={IEEE}
}

- [x] bibtex link confirmed
- [x] pdf done

**Comment by bc** [comment]
![image](https://user-images.githubusercontent.com/13772726/30778568-cdf8abb2-a08d-11e7-8329-8f6b19970748.png)
