### ISSUE TITLE
Conference Paper

### ISSUE THREAD

**Issue by jasmineberry** [usc-bbdl/usc-bbdl.github.io#44]
The neural control of movement must contend with trajectory-specific and nonlinearly distorted manifolds of afferent muscle spindle activity

Papers/[BerryIJCNN17.pdf](https://github.com/usc-bbdl/usc-bbdl.github.io/files/1400134/BerryIJCNN17.pdf)

We introduce the concept of trajectory-specific sensory manifolds. They are the unique multidimensional and time-varying combinations of afferent signals that obligatorily emerge during a limb movement. We use the example of muscle spindles (i.e., the muscle's proprioceptors for length and velocity) that arise during movements of an arm (a planar 2-DOF 6-muscle model) during the production of straight, curved and oscillatory hand movements. Through the use of parallel coordinates, we visualize the high-dimensional evolution of the afferent signaling across muscles and tasks. We demonstrate that a given movement gives rise to a distinct sensory manifold embedded in the 12-D space of spindle information that is largely independent of the choice of muscle coordination strategy. Given that muscle lengths and velocities are fully determined by joint kinematics, such manifolds provide a rich set of information to use in its control.

Berry JA, Ritter R, Nagamori A, Valero-Cuevas, FJ.

"@inproceedings{berry2017neural,
  title={The neural control of movement must contend with trajectory-specific and nonlinearly distorted manifolds of afferent muscle spindle activity},
  author={Berry, Jasmine A and Ritter, Robert and Nagamori, Akira and Valero-Cuevas, Francisco J},
  booktitle={Neural Networks (IJCNN), 2017 International Joint Conference on},
  pages={1188--1194},
  year={2017},
  organization={IEEE}
}
"

2017

IEEE International Joint Conference on Neural Networks (IJCNN) 2017

**Comment by bc** [comment]
Is it a peer reviewed research paper? What section should I put it in?
________________________________

**Comment by jasmineberry** [comment]
Yes it is peer-reviewed.

**Comment by bc** [comment]
so should it be in publications?

**Comment by jasmineberry** [comment]
Yes, it was published in the conference proceedings.

**Comment by bc** [comment]
![image](https://user-images.githubusercontent.com/13772726/35023355-2172a098-faef-11e7-9196-e25358b8ca13.png)
