### ISSUE TITLE
New Publication

### ISSUE THREAD

**Issue by anagamori** [usc-bbdl/usc-bbdl.github.io#46]
Title:
Cardinal features of involuntary force variability can arise from the closed-loop control of viscoelastic afferented muscles

[journal.pcbi.1005884.pdf](https://github.com/usc-bbdl/usc-bbdl.github.io/files/1623981/journal.pcbi.1005884.pdf)

Abstract: 
Author summary Involuntary fluctuations in muscle force are an unavoidable consequence of human motor control and underlie movement execution errors. Amplification and distortion of involuntary force variability are common phenomena found in various neurological conditions and in fatigue. However, the underlying mechanisms for this are often unclear. We investigated the generation and modulation of involuntary force variability arising from different sources, as well as their interactions. We used a closed-loop simulation which included a physiologically-grounded model of an afferented musculotendon and an error-controller. We show that interactions among neural noise, musculotendon mechanics, proprioceptive feedback, and error correction are critical components of force control, and by taking these into account, our model was able to both replicate and explain many cardinal features of involuntary force variability previously reported experimentally. Also, our results suggest previously unrecognized pathways through which force variability may be altered in fatigue and in certain neurological diseases. Finally, we emphasize the potential for important clinical and scientific information to be extracted from relatively simple, non-invasive measurements of force.

Author:
Nagamori A, Laine CM, Valero-Cuevas FJ.

"@article{nagamori2018cardinal,
  title={Cardinal features of involuntary force variability can arise from the closed-loop control of viscoelastic afferented muscles},
  author={Nagamori, Akira and Laine, Christopher M and Valero-Cuevas, Francisco J},
  journal={PLOS Computational Biology},
  volume={14},
  issue = {1},
  year={2018}
}"

Year:
2018

Journal:
PLOS Computational Biology

**Comment by bc** [comment]
tags?
see
https://docs.google.com/spreadsheets/d/18Xno5qeb8pBl2C3h3s4faZ2AkRu27kn5T3F0TPytNFc/edit#gid=0 for examples

**Comment by bc** [comment]
i set tags as neuroscience and modeling
