### ISSUE TITLE
Publication which needs to be added to the website

### ISSUE THREAD

**Issue by marjanin** [usc-bbdl/usc-bbdl.github.io#52]
Delete all nonrelevant information from this template when submitting your issue request:

#Publication
```
Should anthropomorphic systems be "redundant"?
Link (Just add "(Accepted)" at the end. Link is not available yet since it is not published yet)
I sent you the pdf file using email.
Abstract
Author: Ali Marjaninejad and Francisco J. Valero-Cuevas
BibTex: Not out there yet but this is the most accurate that I can give you right now:
Should anthropomorphic systems be "redundant"?, Ali Marjaninejad and Francisco J. Valero-Cuevas, Biomechanics of Anthropomorphic Systems, Eds Gentiane Venture, Jean-Paul Laumond & Bruno Watier, STAR series, Springer, 2018. (in press)
Year: 2018
Journal: It is a book chapter: Biomechanics of Anthropomorphic Systems
SupplementalLink						
Get BibTex Via Google Scholar’s Cite. (not available yet)
``
 ## NOTE:
The format of the Author section is very important to the design of the site. If there’s no supplemental material, just leave it blank.


## Example
```
Unilateral Eccentric Contraction of the Plantarflexors Leads to Bilateral Alterations in Leg Dexterity.

Papers/2016NagamoriFrontPhysiol.pdf

Eccentric contractions can affect musculotendon mechanical properties and disrupt muscle proprioception, but their behavioral consequences are poorly understood. We tested whether repeated eccentric contractions of plantarflexor muscles of one leg affected the dexterity of either leg. Twenty healthy male subjects (27.3 ± 4.0 yrs) compressed a compliant and slender spring prone to buckling with each isolated leg. The maximal instability they could control (i.e., the maximal average sustained compression force, or lower extremity dexterity force, LEDforce) quantified the dexterity of each leg. We found that eccentric contractions did not affect LEDforce, but reduced force variability (LEDSD). Surprisingly, LEDforce increased in the non-exposed, contralateral leg. These effects were specific to exposure to eccentric contractions because an effort-matched exposure to walking did not affect leg dexterity. In the exposed leg, eccentric contractions (i) reduced voluntary error corrections during spring compressions (i.e., reduced 0.5–4 Hz power of LEDforce); (ii) did not change spinal excitability (i.e., unaffected H-reflexes); and (iii) changed the structure of the neural drive to the α-motoneuron pool (i.e., reduced EMG power within the 4–8 Hz physiological tremor band). These results suggest that repeated eccentric contractions alter the feedback control for dexterity in the exposed leg by reducing muscle spindle sensitivity. Moreover, the unexpected improvement in LEDforce in the non-exposed contralateral leg was likely a consequence of crossed-effects on its spinal and supraspinal feedback control. We discuss the implications of these bilateral effects of unilateral eccentric contractions, their effect on spinal and supraspinal control of dynamic foot-ground interactions, and their potential to facilitate rehabilitation from musculoskeletal and neuromotor impairments.

Nagamori A, Valero-Cuevas FJ, Finley JM.

"@article{nagamori2016unilateral,
  title={Unilateral Eccentric Contraction of the Plantarflexors Leads to Bilateral Alterations in Leg Dexterity},
  author={Nagamori, Akira and Valero-Cuevas, Francisco J and Finley, James M},
  journal={Frontiers in Physiology},
  volume={7},
  year={2016},
  publisher={Frontiers Media SA}
}
"

2016

Frontiers in Physiology	
```


# Have an issue with website? (change/removal/addition)
Include:
 - Link to the file where the change needs to happen, exact text, images, etc to include/remove
 - Paste any available quick screenshots
 - Link to the files that will be affected by the change, which you can find via https://github.com/usc-bbdl/usc-bbdl.github.io
 - Urgency = immediately (text me too), within 2 days, or within 5 days)

**Comment by bc** [comment]
[amfvc_chapter2018.pdf](https://github.com/usc-bbdl/usc-bbdl.github.io/files/1662137/amfvc_chapter2018.pdf)

**Comment by bc** [comment]
@marjanin you need to fix the authors, the bibtex is not formatted with the curly braces etc
![image](https://user-images.githubusercontent.com/13772726/35406119-edc1c54c-01bc-11e8-9a23-2c382ba892c3.png)
