### ISSUE TITLE
Adding Gabe Glasser to Valerolab website

### ISSUE THREAD

**Issue by gglasser** [usc-bbdl/usc-bbdl.github.io#54]
Addition
People: Gabe Glasser
Photo: https://drive.google.com/drive/folders/1N2Rj29C7lehPLxWZ6QHlYc_eV1lpBflS
Description: Creating novel, mechanically efficient designs to tendon-driven anthropomorphic robots 
Link: http://valerolab.org/people/

 Urgency: when new photos are updated with for lab profiles

**Comment by bc** [comment]
plz reply with your usc email

**Comment by gglasser** [comment]
gglasser@usc.edu
