### ISSUE TITLE
Picture

### ISSUE THREAD

**Issue by cmlaine** [usc-bbdl/usc-bbdl.github.io#56]
Hi.
For my photo on the lab website...
I would prefer picture ID ....1295.jpg on the shared folder
https://drive.google.com/drive/folders/1N2Rj29C7lehPLxWZ6QHlYc_eV1lpBflS

Thanks,
Chris

**Comment by bc** [comment]
![image](https://user-images.githubusercontent.com/13772726/38222885-81605840-369c-11e8-923e-e5b1991678ab.png)

**Comment by bc** [comment]
verified on deployed
![image](https://user-images.githubusercontent.com/13772726/38222903-9b2e9732-369c-11e8-90b7-967817c96aa3.png)
