### ISSUE TITLE
NCM Abstract

### ISSUE THREAD

**Issue by anagamori** [usc-bbdl/usc-bbdl.github.io#62]
#52 Publication 

**Conference Abstract**
Title: A computational model of afferented muscles reproduces cardinal features of force variability 
Abstract: 
[NCM_Abstract_AN.pdf](https://github.com/usc-bbdl/usc-bbdl.github.io/files/2031988/NCM_Abstract_AN.pdf)

Author: Nagamori A, Laine CM, Valero-Cuevas FJ
BibTex: 
@inproceedings{nagamori2018computational,
    title={A computational model of afferented muscles reproduces cardinal features of force variability },
    author = {Nagamori, Akira and Laine, Christopher M and Valero-Cuevas, Francisco J},
    booktitle = {Proceedings of the 28th Annual Meeting of the Society for the Neural Control of Movement (Santa Fe, New Mexico, USA, May 2018)},
    year = {2018}
}
Year: 2018
Journal: Proceedings of the 28th Annual Meeting of the Society for the Neural Control of Movement (Santa Fe, New Mexico, USA, May 2018)

**Comment by bc** [comment]
![image](https://user-images.githubusercontent.com/13772726/40459731-e4dc3892-5eb7-11e8-9d73-52169a10654f.png)
