### ISSUE TITLE
Please add to the website. Thanks!

### ISSUE THREAD

**Issue by marjanin** [usc-bbdl/usc-bbdl.github.io#68]
An Analytical Approach to Posture-Dependent Muscle Force and Muscle Activation Patterns
Link: I dragged and dropped the file here

Abstract:
Personalized training by taking into account individual anatomy to improve performance is a research frontier. In this paper, we first introduce an analytical method to study the pattern of changes in muscle forces as a function of posture. Our method is also able to analyze variation of maximal muscle force and muscle activation values (in various postures) as a result of posture-dependent changes in moment arms. This method also helps us evaluate the utility of person specific training. It also provides us with model based approximations for activation and muscle force patterns during different motions without a need for subject recordings, which enables athletes to have a better understanding of how each muscle contributes during each posture, in a fast and efficient way. Second, we analyze the results of this method for a simple squat move. Our results show that both maximal muscle force and muscle activation values have variable sensitivity to the moment arm values for different postures and muscles. It suggests that individually modified training plans could likely improve performance for some sets of movements.

Authors:
Marjaninejad, Ali and Berry, Jasmine A and Valero-Cuevas, Francisco J

BibTex:
@inproceedings{marjaninejad2018An,
  title={An Analytical Approach to Posture-Dependent Muscle Force and Muscle Activation Patterns},
  author={Marjaninejad, Ali and Berry, Jasmine A and Valero-Cuevas, Francisco J},
  booktitle={Conference proceedings:... Annual International Conference of the IEEE Engineering in Medicine and Biology Society. IEEE Engineering in Medicine and Biology Society. Annual Conference},
  volume={2018},
  pages={},
  year={2018}
}
[EMBC18_1241_FI_ac.pdf](https://github.com/usc-bbdl/usc-bbdl.github.io/files/2239121/EMBC18_1241_FI_ac.pdf)

Year: 2018
Journal: IEEE EMBC 2018 Proceedings

**Comment by marjanin** [comment]
The PDF file is now updated.
This issue is now ready to be processed.
Please upload the publication to the valerolab.org. Thanks!

**Comment by bc** [comment]
Marjaninejad, Ali and Berry, Jasmine A and Valero-Cuevas, Francisco J
should be
Marjaninejad, A, Berry, JA, and Valero-Cuevas FJ

**Comment by bc** [comment]
loaded onto CSV ✔️
