### ISSUE TITLE
Please add this one too. Thanks!

### ISSUE THREAD

**Issue by marjanin** [usc-bbdl/usc-bbdl.github.io#69]
Title: Model-Free Control of Movement in a Tendon-Driven Limb via a Modified Genetic Algorithm

File: I drag and dropped it here

Abstract:
Tendon-driven systems have many benefits over other actuation strategies such as torque-driven systems; however, their over-determined nature and posture-dependent actuation presents strong constraints on their control. Also, parameters or even exact structure of the model in these systems, especially in the biological ones, are normally not clear to the controller. Here, we propose a modified Genetic Algorithm that provides the tendon excursion values for the limb to follow a desired trajectory. Our results show that the proposed algorithm was able to accurately follow the desired trajectory without the model of the system being exposed to it. We believe that this method can enable biologically inspired tendon-driven mechanisms with variable mechanical structures to autonomously control their movements.

Authors:
Marjaninejad, Ali and Annigeri, Rohit A and Valero-Cuevas, Francisco J

BibTex:
@inproceedings{marjaninejad2018Model,
  title={Model-Free Control of Movement in a Tendon-Driven Limb via a Modified Genetic Algorithm},
  author={Marjaninejad, Ali and Annigeri, Rohit A and Valero-Cuevas, Francisco J},
  booktitle={Conference proceedings:... Annual International Conference of the IEEE Engineering in Medicine and Biology Society. IEEE Engineering in Medicine and Biology Society. Annual Conference},
  volume={2018},
  pages={},
  year={2018}
}

Year: 2018

Journal: IEEE EMBC 2018 Proceedings

SupplementalLink:
https://github.com/marjanin/GA_T
[EMBC18_1382_FI_ac.pdf](https://github.com/usc-bbdl/usc-bbdl.github.io/files/2239119/EMBC18_1382_FI_ac.pdf)

**Comment by marjanin** [comment]
The PDF file is now updated.
This issue is now ready to be processed.
Please upload the publication to the valerolab.org. Thanks!

**Comment by bc** [comment]
Marjaninejad, Ali and Annigeri, Rohit A and Valero-Cuevas, Francisco J
Marjaninejad, A, Annigeri, RA, and Valero-Cuevas, FJ

**Comment by bc** [comment]
added to csv ✔️
