### ISSUE TITLE
The typo of the paper is now fixed

### ISSUE THREAD

**Issue by marjanin** [usc-bbdl/usc-bbdl.github.io#70]
Hi Brian,
Here is the updated PDF.
The typo is now fixed.
Please sub this with the one we have on the website now.
Thank you!
- Ali
[TendonDriven_GA__Accepted__ver__Final_fixed.pdf](https://github.com/usc-bbdl/usc-bbdl.github.io/files/2284818/TendonDriven_GA__Accepted__ver__Final_fixed.pdf)

**Comment by bc** [comment]
fixed, but the other paper for IEEE EMBC also has this exact issue
