### ISSUE TITLE
Get picture/figure for each project

### ISSUE THREAD

**Issue by briancohn** [usc-bbdl/usc-bbdl.github.io#8]
- [x] Meng-Fen Tsai 
- [x] Brian Cohn    Statistical Control & ML
- [x] Ali Marjaninejad  Brain-Machine-Interface
- [x] Chris Laine   Tremor
- [x] Chris Laine   Cortical Coherence
- [x] Chris Laine   Ecog
- [x] Ko    TMS/ ParkinsonsDisease
- [x] Emily SD test
- [ ] Akira SD - Eccentric
- [x] Kian  Neuromorphic + Neuromechanics
- [x] Suraj Neuromorphic Computing
- [ ] Jun   Data Capture
- [x] Daniel    Neural Control of Movement
- [ ] Victor    Neuromorphic pet

**Comment by briancohn** [comment]
@danhagen try to get a high quality version of every one (preferably pdf or PNG ) can be a pic or a figure

**Comment by briancohn** [comment]
Here's mine @danhagen 
[parcoord_alpha50.pdf](https://github.com/usc-bbdl/usc-bbdl.github.io/files/175844/parcoord_alpha50.pdf)

**Comment by danhagen** [comment]
@bcohn12 

Meng-Fen: 
![loadcellapparatus meng_fen](https://cloud.githubusercontent.com/assets/16945786/13819835/3032584c-eb58-11e5-9a0f-b2c4e196e31b.jpg)
![timdata meng_fen](https://cloud.githubusercontent.com/assets/16945786/13819848/3cb3e522-eb58-11e5-8e2d-791b169aeb3d.png)

Ali:
![bmi ali](https://cloud.githubusercontent.com/assets/16945786/13819869/4d4d388e-eb58-11e5-86ee-b5e4c084aaa2.png)

Chris (all):
[All.Chris.pptx](https://github.com/usc-bbdl/usc-bbdl.github.io/files/176392/All.Chris.pptx)

Hannah (Ko):
[BrainWithTMScoil.Hannah.pdf](https://github.com/usc-bbdl/usc-bbdl.github.io/files/176393/BrainWithTMScoil.Hannah.pdf)
[SpringHand.Hannah.pdf](https://github.com/usc-bbdl/usc-bbdl.github.io/files/176394/SpringHand.Hannah.pdf)

Emily:
[ConvHull_Athletes.Emily.pdf](https://github.com/usc-bbdl/usc-bbdl.github.io/files/176413/ConvHull_Athletes.Emily.pdf)
[Fig2_Lorenz.Emily.pdf](https://github.com/usc-bbdl/usc-bbdl.github.io/files/176415/Fig2_Lorenz.Emily.pdf)
[Fig4_ReconstructedAttractor.Emily.pdf](https://github.com/usc-bbdl/usc-bbdl.github.io/files/176414/Fig4_ReconstructedAttractor.Emily.pdf)
[CompFigs.Emily.pdf](https://github.com/usc-bbdl/usc-bbdl.github.io/files/176412/CompFigs.Emily.pdf)

Kian:
[CadaverGammaReflex.Kian.pdf](https://github.com/usc-bbdl/usc-bbdl.github.io/files/176416/CadaverGammaReflex.Kian.pdf)

Daniel:
[3Trajectories.Dan.pdf](https://github.com/usc-bbdl/usc-bbdl.github.io/files/176420/3Trajectories.Dan.pdf)
[3TrajectoriesWithHist.Dan.pdf](https://github.com/usc-bbdl/usc-bbdl.github.io/files/176421/3TrajectoriesWithHist.Dan.pdf)

**Comment by danhagen** [comment]
Suraj:
![assembly suraj](https://cloud.githubusercontent.com/assets/16945786/14032808/a7092236-f1d2-11e5-9181-197db17845bb.jpg)
![fpga_one_channel suraj](https://cloud.githubusercontent.com/assets/16945786/14032812/aaabd636-f1d2-11e5-9251-ac5f4280cac8.jpg)
![schematic suraj](https://cloud.githubusercontent.com/assets/16945786/14032815/aeda156a-f1d2-11e5-8c4a-85b0ca3387a6.png)
