### ISSUE TITLE
upload paper to website

### ISSUE THREAD

**Issue by cmlaine** [usc-bbdl/usc-bbdl.github.io#81]
Title:  Parkinson's Disease Exhibits Amplified Intermuscular Coherence During Dynamic Voluntary 
Link:  https://www-ncbi-nlm-nih-gov.libproxy1.usc.edu/pmc/articles/PMC7145888/
Abstract:  Parkinson’s disease (PD) is typically diagnosed and evaluated on the basis of overt motor dysfunction, however, subtle changes in the frequency spectrum of neural drive to muscles have been reported as well. During dynamic actions, coactive muscles of healthy adults often share a common source of 6-15 Hz (alpha-band) neural drive, creating synchronous alpha-band activity in their EMG signals. Individuals with PD commonly exhibit kinetic action tremor at similar frequencies, but the potential relationship between the intermuscular alpha-band neural drive seen in healthy adults and the action tremor associated with PD is not well understood. A close relationship is most tenable during voluntary dynamic tasks where alpha-band neural drive is strongest in healthy adults, and where neural circuits affected by PD are most engaged. In this study, we characterized the frequency spectrum of EMG synchronization (intermuscular coherence) in 16 participants with PD and 15 age-matched controls during two dynamic motor tasks: 1) rotation of a dial between the thumb and index finger, and 2) dynamic scaling of isometric precision pinch force. These tasks produce different profiles of coherence between the first dorsal interosseous and abductor pollicis brevis muscles. We sought to determine if alpha-band intermuscular coherence would be amplified in participants with PD relative to controls, if such differences would be task-specific, and if they would correlate with symptom severity. We found that relative to controls, the PD group displayed amplified, but similarly task-dependent, coherence in the alpha-band. The magnitude of coherence during the rotation task correlated with overall symptom severity as per the UPDRS rating scale. Finally, we explored the potential for our coherence measures, with no additional information, to discriminate individuals with PD from controls. The area under the Receiver Operating Characteristic curve (AUC) indicated a clear separation between groups (AUC = 0.96), even though participants with PD were on their typical medication and displayed only mild-moderate symptoms. We conclude that a task-dependent, intermuscular neural drive within the alpha-band is amplified in PD. Its quantification via intermuscular coherence analysis may provide a useful tool for detecting the presence of PD, or assessing its progression.
Author: Laine, CM, Valero-Cuevas, FJ.

BibTex:
@ARTICLE{10.3389/fneur.2020.00204,
  
AUTHOR={Laine, Christopher M. and Valero-Cuevas, Francisco J.},   
	 
TITLE={Parkinson's Disease Exhibits Amplified Intermuscular Coherence During Dynamic Voluntary Action},      
	
JOURNAL={Frontiers in Neurology},      
	
VOLUME={11},      

PAGES={204},     
	
YEAR={2020},      
	  
URL={https://www.frontiersin.org/article/10.3389/fneur.2020.00204},       
	
DOI={10.3389/fneur.2020.00204},      
	
ISSN={1664-2295},   
   
ABSTRACT={Parkinson's disease (PD) is typically diagnosed and evaluated on the basis of overt motor dysfunction, however, subtle changes in the frequency spectrum of neural drive to muscles have been reported as well. During dynamic actions, coactive muscles of healthy adults often share a common source of 6–15 Hz (alpha-band) neural drive, creating synchronous alpha-band activity in their EMG signals. Individuals with PD commonly exhibit kinetic action tremor at similar frequencies, but the potential relationship between the intermuscular alpha-band neural drive seen in healthy adults and the action tremor associated with PD is not well-understood. A close relationship is most tenable during voluntary dynamic tasks where alpha-band neural drive is strongest in healthy adults, and where neural circuits affected by PD are most engaged. In this study, we characterized the frequency spectrum of EMG synchronization (intermuscular coherence) in 16 participants with PD and 15 age-matched controls during two dynamic motor tasks: (1) rotation of a dial between the thumb and index finger, and (2) dynamic scaling of isometric precision pinch force. These tasks produce different profiles of coherence between the first dorsal interosseous and abductor pollicis brevis muscles. We sought to determine if alpha-band intermuscular coherence would be amplified in participants with PD relative to controls, if such differences would be task-specific, and if they would correlate with symptom severity. We found that relative to controls, the PD group displayed amplified, but similarly task-dependent, coherence in the alpha-band. The magnitude of coherence during the rotation task correlated with overall symptom severity as per the UPDRS rating scale. Finally, we explored the potential for our coherence measures, with no additional information, to discriminate individuals with PD from controls. The area under the Receiver Operating Characteristic curve (AUC) indicated a clear separation between groups (AUC = 0.96), even though participants with PD were on their typical medication and displayed only mild-moderate symptoms. We conclude that a task-dependent, intermuscular neural drive within the alpha-band is amplified in PD. Its quantification via intermuscular coherence analysis may provide a useful tool for detecting the presence of PD, or assessing its progression.}
}

[Laine and Valero-Cuevas - 2020 - Parkinson's Disease Exhibits Amplified Intermuscul.pdf](https://github.com/usc-bbdl/usc-bbdl.github.io/files/4596145/Laine.and.Valero-Cuevas.-.2020.-.Parkinson.s.Disease.Exhibits.Amplified.Intermuscul.pdf)

**Comment by bc** [comment]
![image](https://user-images.githubusercontent.com/13772726/81619469-842ed900-939e-11ea-9a16-649b84be0eb9.png)
